AWSTemplateFormatVersion: 2010-09-09
Description: >-
  blog-server

Transform:
- AWS::Serverless-2016-10-31

Resources:
  helloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/hello-world.handler
      Runtime: nodejs12.x
      MemorySize: 128
      Timeout: 100
      Description: Hello World
      Events:
        Api:
          Type: Api
          Properties:
            Path: /
            Method: GET

  getBlogFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/get-blog.handler
      Runtime: nodejs12.x
      Layers:
        - arn:aws:lambda:us-east-1:654733764120:layer:aws-sdk:1
      MemorySize: 128
      Timeout: 100
      Description: Get Blog
      Events:
        Api:
          Type: Api
          Properties:
            Path: /b
            Method: GET
      Policies:
        - S3ReadPolicy:
          BucketName: jbasten-blog