AWSTemplateFormatVersion: 2010-09-09
Description: >-
  blog-server

Transform:
- AWS::Serverless-2016-10-31

Resources:
  healthCheckFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/healthCheck.handler
      Runtime: nodejs12.x
      Role: arn:aws:iam::654733764120:role/lambdaRole
      MemorySize: 128
      Timeout: 100
      Description: Health Check
      Layers:
        - arn:aws:lambda:us-east-1:654733764120:layer:blog-server-layer
      Events:
        Api:
          Type: Api
          Properties:
            Path: /
            Method: GET

  getBlogFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/getBlog.handler
      Runtime: nodejs12.x
      Role: arn:aws:iam::654733764120:role/lambdaRole
      MemorySize: 128
      Timeout: 100
      Description: Get Blog
      Layers:
        - !Ref BlogServerLayer
      Events:
        Api:
          Type: Api
          Properties:
            Path: /blog/{id}
            Method: GET

  BlogServerLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: blog-server-layer
      Description: Dependencies for sam app blog-server
      ContentUri: s3://jbasten-serverless-artifacts/blog-server-lambda-layer.zip
      CompatibleRuntimes:
        - nodejs12.x
      RetentionPolicy: Retain