version: 2.1

orbs:
  sam: circleci/aws-sam-serverless@2.1.0

workflows:
  test_and_deploy:
    jobs:
      - sam/deploy:
          name: deploy
          stack-name: blog-server
          template: template.yml