version: 2.1

orbs:
  sam: circleci/aws-sam-serverless@2.1.0

workflows:
  build_and_deploy:
    jobs:
      - sam/deploy:
          name: deploy
          stack-name: blog-server
          template: template.yml
          s3-bucket: $AWS_ARTIFACT_BUCKET
          environment:
            - BLOG_MONGO_CONNECTION: $BLOG_MONGO_CONNECTION
