version: 2.1

install_aws_cli: &install_aws_cli
  name: Install AWS CLI
  command: pip install awscli --upgrade

orbs:
  sam: circleci/aws-sam-serverless@2.1.0

jobs:
  compile_with_typescript:
    working_directory: ~/blog-server
    docker:
      - image: node:15.3.0
    steps:
      - checkout
      - run:
          name: Install Typescript
          command: npm install typescript
      - run:
          name: Compile
          command: npm run compile
      - persist_to_workspace:
          root: ~/blog-server
          paths: .

  build_lambda_layer:
    working_directory: ~/blog-server/src/lambda-layer
    docker:
      - image: node:15.3.0
    steps:
      - run:
          name: Install Packages
          command: npm install
      - persist_to_workspace:
          root: ~/blog-server/src/lambda-layer
          paths: .

  deploy_lambda_layer:
    working_directory: ~/blog-server
    docker:
      - image: cimg/python:3.7
    steps:
      - run:
          <<: *install_aws_cli
      - run:
          name: Where am i
          command: echo $PWD && ls
      - run:
          name: Zip Lambda Layer
          command: zip -r blog-server-lambda-layer.zip src/lambda-layer
      - run:
          name: Deploy Lambda Layer Zip to S3
          command: aws s3 cp blog-server-lambda-layer.zip s3://jbasten-serverless-artifacts
      - run:
          name: Publish Lambda Layer
          command: aws lambda publish-layer-version \
            --layer-name blog-server-layer \
            --description "Dependencies for blog-server" \
            --content S3Bucket=jbasten-serverless-artifacts,S3Key=blog-server-lambda-layer.zip \
            --compatible-runtimes nodejs12.x

workflows:
  build-and-deploy:
    jobs:
      - compile_with_typescript
      - build_lambda_layer:
          requires:
            - compile_with_typescript
      - deploy_lambda_layer:
          requires:
            - build_lambda_layer
      - sam/deploy:
          name: build_and_deploy_sam_app
          context:
            - BLOG_PROD
          stack-name: blog-server
          template: template.yml
          s3-bucket: jbasten-serverless-artifacts
          requires:
            - deploy_lambda_layer