version: 2.1

orbs:
  sam: circleci/aws-serverless@1.0.1

workflows:
  build_and_deploy:
    jobs:
      - sam/deploy:
          name: deploy-production
          s3-bucket: $AWS_ARTIFACT_BUCKET
          stack-name: blog-server
          template: template.yaml